### ISSUE TITLE
Star a song

### ISSUE THREAD

**Issue by cyberbalsa** [andruzzzhka/BeatSaverDownloader#3]
You can login a user and get a API key by posting data to https://www.beatsaver.com/api.php?mode=votekey the raw post data should be "username=$user&password=$password"

you will get a string back, just pass it back to 

https://www.beatsaver.com/vote.php?id=$songid&token=$votetoken as a GET reqyest

**Comment by xyonico** [comment]
@JRWR Since logging in in VR is basically impossible and sending password unhashed is not a good idea, what about linking BeatSaver accounts with Steam and Oculus users? That way this plugin and any other plugin can instead send a Steam session ticket and whatever Oculus uses and login automatically that way?

**Comment by cyberbalsa** [comment]
Well, Since its over HTTPS, and its the same methods a browser would be using to send a password thats a moot point

--- the votekey can only be used for staring tracks and it permanent,  you would only need to login once

**Comment by Byorun** [comment]
where would you save your vote key? Putting it inside the Beatsaber folder would enable all mods to read it  but on the other hand that key only enables you to vote for a song.

**Comment by cyberbalsa** [comment]
Right, thats the point in it, its not really that big of a secret to guard
