### ISSUE TITLE
"Request Timeout" error raised on all download attempts.

### ISSUE THREAD

**Issue by LukeusMaximus** [andruzzzhka/BeatSaverDownloader#7]
I don't have any further details. Any idea how to diagnose this one?

**Comment by ocbaker-fabric** [comment]
I'm pretty sure the issue is internet speed. The "Request Timeout" happens always after a fixed period of time and happens regardless of internet activity.

I have 11mbps internet and some of the larger songs take longer to download than the time given so it just cancels the download and tells you there was a timeout.

The developer needs to change this so that it only timesout if a download isn't actually happening, not everyone will have fast internet and I'm sure there are people with even less than 11mbps.
